### ISSUE TITLE
Skill graph is completely off

### ISSUE THREAD

**Issue by L-as** [NS2CDT/NS2Plus#14]
Example file: [LastRoundStats.json](https://github.com/NS2CDT/NS2Plus/files/2266469/LastRoundStats.txt)

The entire game aliens had nearly 300 skill more, yet it was not recorded like that.

**Comment by ghost** [comment]
Line 2353: local avgTeam1Skill, avgTeam2Skill = hiveSkill[1]/curMaxPlayers, hiveSkill[2]/curMaxPlayers

needs to be something like: 

local avgTeam1Skill, avgTeam2Skill = hiveSkill[1]/players[1] > 0 and players[1] or 1, hiveSkill[2]/players[2] > 0 and players[2] or 1

Currently the team hiveskill is divided by the max amount of players of either team.
