### ISSUE TITLE
Ability to tweak new Alien Vision Parameters

### ISSUE THREAD

**Issue by 0sm1um** [NS2CDT/NS2Plus#19]
In 235, we introduced a new version of Alien Vision which made marines structures and weapons blue, as well as highlighting teammates and friendly structures green.

I've heard numerous players request that these parameters be customizable in NS2+

**Comment by GhoulofGSG9** [comment]
https://github.com/NS2CDT/NS2Plus/pull/28 should have taken care of this issue
