### ISSUE TITLE
Ambient map sounds are not disabled by the NS2+ option

### ISSUE THREAD

**Issue by GhoulofGSG9** [NS2CDT/NS2Plus#2]
<a href="https://github.com/keatsandyeats"><img src="https://avatars0.githubusercontent.com/u/8346964?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [keatsandyeats](https://github.com/keatsandyeats)**
_Friday Jun 30, 2017 at 03:06 GMT_
_Originally opened as https://github.com/sclark39/NS2Plus/issues/42_

----

Actually, sometimes they are. I don't know what turns them off or on.

Not sure how long this has been broken. Maybe a month or two.

**Comment by GhoulofGSG9** [comment]
<a href="https://github.com/keatsandyeats"><img src="https://avatars0.githubusercontent.com/u/8346964?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [keatsandyeats](https://github.com/keatsandyeats)**
_Sunday Oct 22, 2017 at 19:05 GMT_

----

still trying to track this down. I hear noises as spectator but `mapinfo` says 0 ambient sounds

**Comment by GhoulofGSG9** [comment]
<a href="https://github.com/keatsandyeats"><img src="https://avatars0.githubusercontent.com/u/8346964?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [keatsandyeats](https://github.com/keatsandyeats)**
_Friday Jan 12, 2018 at 00:23 GMT_

----

the game now has `s_stats` so maybe this can be investigated further

**Comment by Handschuuh** [comment]
Is that issue still prevalent? I haven't noticed any issues.
